Preliminary RustDesk inventory support
glpi-project/glpi-agent pull request #193
Opened 2022-08-08 15:46 UTC by paspo

A simple inventory support for [rustdesk](https://rustdesk.com/), an open-source remote management tool.
I took a lot of inspiration from the AnyDesk counterpart.

2022-08-08 16:06 UTC, g-bougard requested changes
Hi @paspo 

thank you for your submission.

I see a little changed needed as `_get_rustdesk_config()` will always return the expected path of the config for the current OS.
The big proposed patch in `doInventory()` is just to remove the loop.

Supporting a list of configuration files make sense only if we really provide a list in some case.

2022-08-08 16:06 UTC, g-bougard commented on lib/GLPI/Agent/Task/Inventory/Generic/Remote_Mgmt/RustDesk.pm
> +    return grep { has_file($_) } @configs;
Here you should better just return the config file path expected on the current OS.
```suggestion
    return OSNAME eq 'MSWin32' ?
        'C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config\RustDesk.toml' :
        '/root/.config/rustdesk/RustDesk.toml';
```

2022-08-08 16:06 UTC, g-bougard commented on lib/GLPI/Agent/Task/Inventory/Generic/Remote_Mgmt/RustDesk.pm
> +    return _get_rustdesk_config() ? 1 : 0;
With the upper change, you should modify here:
```suggestion
    return has_file(_get_rustdesk_config());
```

2022-08-08 16:06 UTC, g-bougard commented on lib/GLPI/Agent/Task/Inventory/Generic/Remote_Mgmt/RustDesk.pm
> +    }
Here you don't need a loop as you expect only one value from _get_rustdesk_config():
```suggestion
    my $conf = _get_rustdesk_config();
    my $RustDeskID = getFirstMatch(
        file    => $conf,
        logger  => $logger,
        pattern => qr/^id\s*=\s*'(.*)'$/
    );

    if (defined($RustDeskID)) {
        $logger->debug('Found RustDesk ID : ' . $RustDeskID) if $logger;

        $inventory->addEntry(
            section => 'REMOTE_MGMT',
            entry   => {
                ID   => $RustDeskID,
                TYPE => 'rustdesk'
            }
        );
    } else {
        $logger->debug('RustDesk ID not found in '.$conf) if $logger;
    }
```

2022-08-08 16:47 UTC, paspo commented
@g-bougard thanks a lot for the (blazing fast) review!

2022-08-09 07:53 UTC, g-bougard commented
Hi @paspo 
yes, glpi-project/glpi#12406 is still needed. I'll keep this PR opened until glpi one is merged.

2022-08-09 07:53 UTC, g-bougard approved these changes

2022-08-10 06:50 UTC, paspo commented
> I'll keep this PR opened until glpi one is merged.

the other PR got accepted.

2022-08-10 08:25 UTC, merged

2022-11-23 08:55 UTC, billgatos commented
Hi all,

Using Nightly latest as today, i get in my local json file after inventory the info for rustdesk id

<REMOTE_MGMT>
<ID>99999999</ID>
<TYPE>anydesk</TYPE>
</REMOTE_MGMT>
<REMOTE_MGMT>
<ID>99999999</ID>
<TYPE>rustdesk</TYPE>
</REMOTE_MGMT>

But that info isn't loaded to glpi ?????

any thoughts on this .

Best regards.

2022-11-24 16:41 UTC, billgatos commented
hi all,

The following recepie works:
GLPI 10.0.5 and agent 1.5 nightly gets the rustdesk id to GLPI asset.