use getPCIDevices() to include missed videos cards
glpi-project/glpi-agent pull request #218
Opened 2022-09-22 13:40 UTC by biji

related to https://github.com/glpi-project/glpi-agent/pull/217

2022-09-22 16:59 UTC, g-bougard requested changes
Hi @biji 
this is better than previous PR.
Anyway you check PCIID which is not always set... sorry, this is not enough to avoid duplicate entries.

2022-09-22 16:59 UTC, g-bougard commented on lib/GLPI/Agent/Task/Inventory/Linux/Videos.pm
> +        $skipPci = $video->{PCIID};
By now, you should not trust $video->{PCIID} as you have no guaranty it is set.

2022-09-22 17:02 UTC, g-bougard commented
Maybe linux video support should completely be rewritten. I'm still not satisfied by the current implementation as for example we can't trust datas from the Xorg log file.

2022-09-22 17:55 UTC, biji commented
using `lspci` should run on wider system, with wayland or xorg.. but can't detect memory size

2022-10-18 07:16 UTC, g-bougard commented
Replaced by #233

2022-10-18 07:16 UTC, closed without merging